name: 'nexus-publisher-win'
description: 'Publish components to Nexus Repository using Windows PowerShell.'
author: 'dannevesdantas'
branding:
  color: green
  icon: box
inputs:
  uri:
    description: 'Folder location to search for AssemblyInfo.cs or AssemblyInfo.vb files'
    required: true
  username:
    description: 'Version number to set on [AssemblyVersion] and [AssemblyFileVersion] attributes of AssemblyInfo.cs or AssemblyInfo.vb files'
    required: true
  password:
    description: 'Version number to set on [AssemblyVersion] and [AssemblyFileVersion] attributes of AssemblyInfo.cs or AssemblyInfo.vb files'
    required: true
  filename:
    description: 'Folder location to search for AssemblyInfo.cs or AssemblyInfo.vb files'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        $uri = New-Object System.Uri("${{ inputs.uri }}")
        $file = "${{ inputs.filename }}"
        $userName = "${{ inputs.username }}"
        $password = ConvertTo-SecureString "${{ inputs.password }}" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($userName, $password)
        Invoke-WebRequest -Uri $uri -InFile $file -Method Put -Credential $credential -UseBasicParsing
      shell: powershell
      